// src/Board.vue
<!-- src/Board.vue -->
<script>
import Square from './Square.vue'
import { calculateWinner } from './lib/game-logic'

export default {
  components: { Square },
  props: {
    api: { type: Object, required: true }
  },
  data: () => ({
    squares: new Array(9).fill(''),
    winner: null
  }),
  methods: {
    handleClick (i) {
      if (this.squares[i] || this.winner) return ''
      this.squares[i] = this.api.getPlayer()
      this.api.commitMove(this.winner = calculateWinner(this.squares))
      return this.squares[i]
    }
  }
}
</script>

<template>
  <div>
    <div v-for="r in 3" class="board-row">
      <Square v-for="c in 3" :api="{handleClick}" :key="3*(r-1)+c-1" />
    </div>
  </div>
</template>

// src/Board.svelte
<!-- src/Board.svelte -->
<script>
import Square from './Square.svelte'
import { calculateWinner } from './lib/game-logic'

export let api
const { commitMove, getPlayer } = api
const squares = new Array(9).fill('')
const triad = [0, 1, 2]
let winner

const handleClick = (i) => {
  if (squares[i] || winner) return ''
  squares[i] = getPlayer()
  commitMove(winner = calculateWinner(squares))
  return squares[i]
}
</script>

<div>
  {#each triad as row}
    <div class="board-row">
      {#each triad as col}
        <Square api={ {handleClick} } id={ 3 * row + col } />
      {/each}
    </div>
  {/each}
</div>
