// src/Square.vue
<!-- src/Square.vue -->
<script>
export default {
  props: {
    api: { type: Object, required: true }
  },
  data: () => ({ mark: '' }),
  methods: {
    onClick () {
      this.mark = this.api.handleClick(this.$vnode.key)
    }
  },
  updated () {              //  Redraw monitoring.
    console.log('updated', this.$vnode.key)
  }
}
</script>

<template>
  <button class="square" @click="onClick">{{ mark }}</button>
</template>

// src/Square.svelte
<!-- src/Square.svelte -->
<script>
import { afterUpdate } from 'svelte'

export let api, id

let mark = ''

afterUpdate(() => console.log('updated', id))       //  Redraw monitoring.

const onClick = () => (mark = api.handleClick(id))
</script>

<button class="square" on:click={ onClick }>
  { mark }
</button>
